title: My GitHub Pages Site
description: Welcome to my awesome website!
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
twitter_username: yourusername
github_username:  yourusername

# Build settings
markdown: kramdown
